package com.elif.entities.notification.enums;

public enum NotificationType {
    COMMUNITY_POST_CREATED,
    COMMUNITY_POST_COMMENT,
    COMMUNITY_COMMENT_REPLY,
    COMMUNITY_CHAT_MESSAGE,
    COMMUNITY_POST_MENTION,
    COMMUNITY_COMMENT_MENTION,
    COMMUNITY_CHAT_MENTION,
    // Notifications de liste d'attente
    WAITLIST_OFFER,
    WAITLIST_EXPIRED,
    WAITLIST_CONFIRMED_BY_USER,

    // Notifications d'inscription (compétition)
    REGISTRATION_PENDING,
    REGISTRATION_APPROVED,
    REGISTRATION_REJECTED,
    REGISTRATION_CANCELLED,
    REGISTRATION_CONFIRMED,
    EVENT_REMINDER
}
