package com.elif.entities.notification.enums;

public enum NotificationType {
    COMMUNITY_POST_CREATED,
    COMMUNITY_POST_COMMENT,
    COMMUNITY_COMMENT_REPLY,
    COMMUNITY_CHAT_MESSAGE,
    COMMUNITY_POST_MENTION,
    COMMUNITY_COMMENT_MENTION,
    COMMUNITY_CHAT_MENTION
}
